In [313]:
from CryptoScraper import cryptoDownloader, getAllData
import pandas as pd
from data_utils import BasicFunctions, PriceFunctions, addData
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [314]:
dr = getAllData(cacheOnly=True, how='intersect')

In [315]:
coinDf = dr.data()

Getting BTC data
Getting DASH data
Getting DOGE data
Getting ETH data
Getting LTC data
Getting STR data
Getting XMR data
Getting XRP data

In [316]:
pf = PriceFunctions()

In [317]:
coinDf = pf.add_yColumns(coinDf, dateindex=False)

In [318]:
coinDf['LTC'].sample(5)

,Date,Open,Close,High,Low,Volume,Percentage Change,Classification
20214,1511780400,0.009347,0.009358,0.009384,0.009303,34.578874,0.008381,0.0
11956,1482051600,0.004684,0.004668,0.004684,0.004637,5.141596,0.007494,0.0
22307,1519315200,0.019772,0.019570,0.019815,0.019523,38.991477,0.032759,1.0
8834,1470812400,0.006400,0.006420,0.006420,0.006400,8.385038,0.014170,0.0
12504,1484024400,0.004938,0.004900,0.004968,0.004870,63.413104,0.017166,1.0

In [319]:
from TechnicalAnalysis import TechnicalAnalysis

coinDf_24 = {}

for coin in coinDf:
    ta = TechnicalAnalysis(coinDf[coin], Timeframe=[24], coin=coin)
    ta.merge_time(cache=True)
    coinDf_24[coin] = ta.get_dic()['24hour'].reset_index() #because 24 hour reddit data

Read merged data from cache
Read merged data from cache
Read merged data from cache
Read merged data from cache
Read merged data from cache
Read merged data from cache
Read merged data from cache
Read merged data from cache

In [320]:
ad = addData(coinDf_24)
coinDf_24 = ad.data_adder('ta')

Adding ta data for BTC
Read merged data from cache
Read merged data from cache
Read merged data from cache
Adding obv indicator
Adding macd indicator
Adding bollingerband indicator
Adding volumechange indicator
Adding rsi indicator

Adding ta data for DASH
Read merged data from cache
Read merged data from cache
Read merged data from cache
Adding obv indicator
Adding macd indicator
Adding bollingerband indicator
Adding volumechange indicator
Adding rsi indicator

Adding ta data for DOGE
Read merged data from cache
Read merged data from cache
Read merged data from cache
Adding obv indicator
Adding macd indicator
Adding bollingerband indicator
Adding volumechange indicator
Adding rsi indicator

Adding ta data for ETH
Read merged data from cache
Read merged data from cache
Read merged data from cache
Adding obv indicator
Adding macd indicator
Adding bollingerband indicator
Adding volumechange indicator
Adding rsi indicator

Adding ta data for LTC
Read merged data from cache
Read merged data from cache
Read merged data from cache
Adding obv indicator
Adding macd indicator
Adding bollingerband indicator
Adding volumechange indicator
Adding rsi indicator

Adding ta data for STR
Read merged data from cache
Read merged data from cache
Read merged data from cache
Adding obv indicator
Adding macd indicator
Adding bollingerband indicator
Adding volumechange indicator
Adding rsi indicator

Adding ta data for XMR
Read merged data from cache
Read merged data from cache
Read merged data from cache
Adding obv indicator
Adding macd indicator
Adding bollingerband indicator
Adding volumechange indicator
Adding rsi indicator

Adding ta data for XRP
Read merged data from cache
Read merged data from cache
Read merged data from cache
Adding obv indicator
Adding macd indicator
Adding bollingerband indicator
Adding volumechange indicator
Adding rsi indicator

In [321]:
coinDf_24['BTC'].sample(5)

,Open,Close,High,Low,Volume,Percentage Change,Classification,obv,macd14,bollingerband14,volumechange14,rsi14
Date,,,,,,,,,,,,
1513314000,17281.00,17481.00,18111.00,17030.00,47320.492727,0.079851,1,3190065,2300.847208,0.637413,-0.452342,82.289040
1467867600,641.02,636.26,649.68,610.10,62537.306828,0.026128,1,717026,10.069105,-0.542486,-0.426171,42.594105
1494219600,1650.50,1728.50,1739.90,1645.10,22531.637673,0.013188,1,1117441,115.144580,0.891721,2.095124,87.397099
1491800400,1219.10,1210.30,1229.90,1208.00,11384.754227,0.016096,1,906113,29.499961,0.583441,-0.640548,84.432089
1465621200,585.06,628.28,632.90,582.01,53239.437277,0.082803,1,665869,35.842377,1.128284,-0.272062,81.402439

In [322]:
pd.read_csv('data_utils/trends_data/bitcoin.csv').head() #weekly data from reverse

         date  bitcoin  isPartial
0  2018-04-15       14       True
1  2018-04-08       16      False
2  2018-04-01       17      False
3  2018-03-25       18      False
4  2018-03-18       18      False

In [323]:
coinDf_24 = ad.data_adder('google')

Adding google data for BTC
Adding google data for DASH
Adding google data for DOGE
Adding google data for ETH
Adding google data for LTC
Adding google data for STR
Adding google data for XMR
Adding google data for XRP

In [324]:
coinDf_24['BTC'].sample(5)

,Open,Close,High,Low,Volume,Percentage Change,Classification,obv,macd14,bollingerband14,volumechange14,rsi14,Google Trend
Date,,,,,,,,,,,,,
1508043600,5765.00,5610.20,5827.6,5450.00,56066.536155,0.007466,1,1521357,404.602538,0.646099,1.002475,75.322063,48.0
1457326800,404.87,414.23,416.0,404.50,14486.005995,0.011575,0,199482,2.134302,-0.311474,-0.020799,38.907001,4.0
1490158800,1098.40,1025.20,1102.4,985.55,40496.161315,0.024688,0,707250,-22.278949,-0.632104,-0.069916,40.448857,48.0
1476853200,638.35,631.08,644.0,627.84,9288.786069,0.008515,1,632251,8.222446,-0.101737,1.781850,66.178048,4.0
1507179600,4163.10,4327.00,4372.3,4133.00,23903.767257,0.010949,1,1395210,87.499615,0.414741,-0.557225,69.658562,48.0

In [325]:
pd.read_csv('data_utils/wikipedia_data/pageviews.csv').head()

,Date,bitcoin,litecoin,ethereum,dashpay,dogecoin,stellar,ripple,monero
0,2015-07-01,12957.0,276.0,254.0,82.0,1051.0,21.0,294.0,51.0
1,2015-07-02,9802.0,238.0,222.0,73.0,603.0,28.0,315.0,26.0
2,2015-07-03,8307.0,229.0,245.0,71.0,540.0,25.0,223.0,37.0
3,2015-07-04,8947.0,201.0,275.0,60.0,505.0,15.0,134.0,21.0
4,2015-07-05,8692.0,245.0,207.0,80.0,614.0,11.0,176.0,63.0

In [326]:
coinDf_24 = ad.data_adder('wikipedia')

Adding wikipedia data for BTC
Adding wikipedia data for DASH
Adding wikipedia data for DOGE
Adding wikipedia data for ETH
Adding wikipedia data for LTC
Adding wikipedia data for STR
Adding wikipedia data for XMR
Adding wikipedia data for XRP

In [327]:
coinDf_24['ETH'].sample(5)

,Open,Close,High,Low,Volume,Percentage Change,Classification,obv,macd14,bollingerband14,volumechange14,rsi14,Google Trend,Wikipedia View
Date,,,,,,,,,,,,,,
1486443600,0.010982,0.010800,0.011066,0.010796,1574.659441,0.013135,0,-224176,-0.000029,-0.533978,-0.214815,29.711441,73.0,6335.0
1507438800,0.070148,0.066590,0.070200,0.065281,4521.133856,0.079690,0,243094,-0.001382,-0.727840,0.205047,21.685855,73.0,6335.0
1497762000,0.142720,0.140689,0.144111,0.138100,27724.813806,0.003039,0,624939,0.018425,0.442526,-0.463440,79.025754,73.0,6335.0
1499317200,0.101915,0.102850,0.105601,0.100700,15228.337442,0.053968,0,291095,-0.001276,-0.547824,-0.349079,37.625164,73.0,6335.0
1442984400,0.003863,0.003908,0.004000,0.003861,272.695640,0.156682,0,2231,-0.000346,-0.173261,-0.636736,30.088437,0.0,435.0

In [328]:
pd.read_csv('data_utils/blockchain_data/bitcoin/difficulty.csv', header=None).head()

                     0    1
0  2009-01-03 00:00:00  1.0
1  2009-01-05 00:00:00  0.0
2  2009-01-07 00:00:00  0.0
3  2009-01-09 00:00:00  1.0
4  2009-01-11 00:00:00  1.0

In [329]:
coinDf_24 = ad.data_adder('blockchain')

Adding blockchain data for BTC

In [330]:
coinDf_24['BTC'].sample(5)

,Open,Close,High,Low,Volume,Percentage Change,Classification,obv,macd14,bollingerband14,...,difficulty,cost-per-transaction-percent,cost-per-transaction,estimated-transaction-volume-usd,estimated-transaction-volume,hash-rate,miners-revenue,n-transactions,output-volume,transaction-fees
Date,,,,,,,,,,,,,,,,,,,,,
1486184400,1008.40,1025.80,1040.00,1001.60,15419.841835,0.009546,0,887565,30.160769,0.900028,...,3.935676e+11,0.916478,7.037076,2.235518e+08,220498.012623,3.043001e+06,1.935046e+06,286326.0,1.867470e+06,139.353033
1480741200,771.67,764.98,771.68,755.98,5254.799401,0.013219,0,780811,14.087164,0.721726,...,2.861796e+11,0.645338,4.670673,1.695282e+08,222042.408409,2.052749e+06,1.419703e+06,318263.0,1.256009e+06,121.340145
1451970000,433.92,428.68,433.92,425.03,12732.944098,0.026170,1,266691,5.392676,-0.186444,...,1.038803e+11,1.964873,9.487333,8.720515e+07,194388.428571,8.417189e+05,1.774245e+06,187012.0,1.125948e+06,33.256457
1500526800,2314.80,2767.80,2922.00,2292.90,102487.367144,0.018322,0,1347096,-30.474799,1.074613,...,8.045252e+11,0.864965,28.381121,5.338387e+08,201930.152726,6.478893e+06,6.303560e+06,230199.0,2.758481e+06,229.272195
1483765200,839.71,939.80,940.00,819.29,33724.919011,0.058834,0,854938,45.813743,-0.202653,...,3.176884e+11,0.536128,5.842191,2.386166e+08,285713.402576,2.195140e+06,1.583005e+06,284719.0,2.273071e+06,107.136643

In [331]:
coinDf_24 = ad.data_adder('reddit') #add gensim data and all

Adding reddit data for BTC

Adding reddit data for DASH

Adding reddit data for DOGE

Adding reddit data for ETH

Adding reddit data for LTC

Adding reddit data for STR

Adding reddit data for XMR

Adding reddit data for XRP

In [345]:
pd.read_csv('data_utils/reddit_data/readable/Ripple.csv').drop('Unnamed: 0', axis=1).head() #after first step

,created,author,title,url,score,num_comments,flair_text,selftext
0,1255535455,KISteam,Aegon releases $650m of capital,http://www.insuranceerm.com/news-comment/aegon...,1,0,NaN,NaN
1,1316695135,[deleted],On Ripple,http://newmeraire.blogspot.com/2011/09/on-ripp...,1,0,NaN,NaN
2,1346189292,60177756,If you're looking for the Ripple payment syste...,http://www.reddit.com/r/ripplers,3,1,NaN,NaN
3,1361459583,HostFat,Ripple Giveaway!,https://bitcointalk.org/index.php?topic=145506,4,12,NaN,NaN
4,1363923139,ahbritto,Ripple Meetup,http://www.meetup.com/ripple/,11,0,NaN,NaN

In [347]:
pd.read_csv('data_utils/reddit_data/readable/Ripple-24.csv').drop('Unnamed: 0', axis=1).tail() #after second step

           Date                                             Reddit
938  1520053200  title Crypto Experts Weigh in, Predict Big Gai...
939  1520139600  title Ripple CEO and Coinbase president will b...
940  1520226000  title WHY RIPPLE IS ATTRACTING FINANCIAL INSTI...
941  1520312400  title Traders locked and loaded score 5 commen...
942  1520398800  title Complete Unsubstantiated Speculation sco...

In [333]:
coinDf_24['XMR'].sample(5)

,Open,Close,High,Low,Volume,Percentage Change,Classification,obv,macd14,bollingerband14,...,reddit290,reddit291,reddit292,reddit293,reddit294,reddit295,reddit296,reddit297,reddit298,reddit299
Date,,,,,,,,,,,,,,,,,,,,,
1509858000,0.011686,0.012376,0.012438,0.011382,517.252828,0.096656,1,266028,-0.001768,-0.466883,...,-0.017222,-0.082574,-0.045050,0.069644,-0.037204,-0.009570,-0.072316,0.047111,-0.168692,0.176196
1519016400,0.028627,0.027666,0.028990,0.027300,376.446878,0.052019,0,271749,0.000332,-0.388066,...,-0.028923,-0.140953,-0.075463,0.118281,-0.058641,-0.017270,-0.122091,0.078397,-0.284743,0.296198
1481086800,0.009614,0.010410,0.010560,0.009572,2377.842518,0.012646,0,169467,0.000201,-0.124391,...,-0.017188,-0.076734,-0.040705,0.064606,-0.034385,-0.007934,-0.067116,0.042906,-0.152589,0.158979
1508821200,0.015800,0.015757,0.016351,0.015244,616.215502,0.021301,0,270882,-0.001813,-0.081754,...,-0.029314,-0.142013,-0.073770,0.119974,-0.061558,-0.016039,-0.122887,0.079370,-0.286657,0.296822
1456635600,0.001969,0.002009,0.002049,0.001955,342.553398,0.004320,0,-1479,0.000132,0.252550,...,-0.016250,-0.082023,-0.042017,0.067635,-0.035748,-0.010910,-0.068664,0.045130,-0.159978,0.169056

In [334]:
coinDf_24 = ad.data_adder('twitter')

Adding twitter data for BTC

In [337]:
coinDf_24['BTC'].sample(5)

,Open,Close,High,Low,Volume,Percentage Change,Classification,obv,macd14,bollingerband14,...,twitter290,twitter291,twitter292,twitter293,twitter294,twitter295,twitter296,twitter297,twitter298,twitter299
Date,,,,,,,,,,,,,,,,,,,,,
1463374800,456.89,454.14,458.88,451.00,8711.904280,0.000926,0,280904,4.045258,-0.062356,...,-0.169073,-0.372052,0.503482,-1.114695,-0.258437,0.549466,0.784894,-0.301137,-0.194082,0.020914
1447131600,378.75,314.51,383.40,300.28,140420.434784,0.013240,1,-141316,26.137828,-0.548644,...,-0.537279,-0.317273,0.631437,-0.389420,-0.243476,0.240113,0.730635,-0.007985,0.013573,0.153236
1450242000,449.81,452.70,469.99,446.21,48909.193513,0.007019,1,340073,28.234030,0.614064,...,-0.414102,-0.341250,0.422191,-0.940896,-0.342733,0.574422,1.041833,-0.358914,-0.187820,0.138654
1515128400,14920.00,16541.00,17105.00,14817.00,56787.876181,0.002833,1,3175325,320.762740,0.909564,...,0.001041,0.001507,-0.000079,0.000629,-0.000014,0.000228,-0.001128,-0.000413,0.000449,-0.001602
1447304400,318.22,340.34,346.44,317.97,53489.261157,0.009971,0,-23421,18.746717,-0.275917,...,-0.064688,-0.393624,0.568155,-0.788792,-0.569052,0.448978,1.382447,-0.312023,-0.194012,-0.036246

In [339]:
from data_utils import redditManager

In [340]:
redditManager().sql_to_pandas('Ripple')

,created,author,title,url,score,num_comments,flair_text,selftext
0,1255535455,KISteam,Aegon releases $650m of capital,http://www.insuranceerm.com/news-comment/aegon...,1,0,None,
1,1316695135,[deleted],On Ripple,http://newmeraire.blogspot.com/2011/09/on-ripp...,1,0,None,
2,1346189292,60177756,If you're looking for the Ripple payment syste...,http://www.reddit.com/r/ripplers,3,1,None,
3,1361459583,HostFat,Ripple Giveaway!,https://bitcointalk.org/index.php?topic=145506,4,12,None,
4,1363923139,ahbritto,Ripple Meetup,http://www.meetup.com/ripple/,11,0,None,
5,1363932077,ancientworldnow,Spare some Ripples?,None,1,6,None,[removed]
6,1364038121,vbfdsbhrewew,█▓▒50 Bitcoin + Free extra 2 Bitcoin=1199.99 (...,http://www.bitswing.com/index.php?main_page=,1,0,None,
7,1364181731,gresaghershre,█▓▒50 Bitcoin + Free extra 2 Bitcoin=1199.99 (...,None,1,0,None,[removed]
8,1364558848,ripper2345,Upcoming on Ripple - Peer-Assisted Key Derivat...,None,1,0,None,[removed]
9,1365697233,ericnakagawa,The promise of Ripple,http://blogs.reuters.com/felix-salmon/2013/04/...,8,0,None,
10,1365697265,ericnakagawa,New website launched for Ripple,http://ripple.com,5,0,None,
11,1365704165,bitaccumulation,Ripple vs Ripplers,None,1,7,None,What is the difference between these two subre...
12,1365726978,[deleted],Did the Ripple team sell any of your bitcoins ...,None,1,0,None,
13,1365738433,WVBitcoinBoy,"The XRP ""beg"" thread?",None,1,0,None,[removed]
14,1365777348,btc4ripple,Trading Ripples for Bitcoins and free Ripple A...,None,2,18,None,"Hey guys, I'm currently have a bunch of Ripple..."
15,1365786330,ericnakagawa,"Why Bitcoin crashed, and how Ripple might avoi...",http://gigaom.com/2013/04/12/why-bitcoin-crash...,1,1,None,
16,1365857870,ftyrftydftred,█▓▒50 Bitcoin + Free extra 2 Bitcoin=$2299 (ww...,None,1,0,None,[removed]
17,1365961592,specialenmity,Ripple is decentralized but will that stop FIN...,None,4,9,None,Just curious. I think ripple holds promise but...
18,1366117802,JerriZA,Hello Ripplers - Just some questions,None,1,0,None,[removed]
19,1366125005,real225,Ripple,http://www.ripplep2p.com/hello-world/,1,0,None,
20,1366139892,NemoNoko,"""Ripple is what happens when money finally mee...",https://ripple.com/blog/interview-with-chris-l...,11,0,None,
21,1366163073,TBtheG,Just got a Ripple wallet. What's the best way ...,None,1,0,None,[removed]
22,1366165820,spitteler,"Help, Can't access previously created wallet o...",None,0,0,None,I created a Ripple wallet on my Laptop and sav...
23,1366236294,nomothetique,So I signed up... for a mailing list?,None,1,0,None,[removed]
24,1366268165,Trading_,I'm buying XRPs ripples ripple,None,1,0,None,[removed]
25,1366304346,bitpiggy,"Why would Ripple prevent ""Situations like in C...",None,1,0,None,[removed]
26,1366317035,HostFat,Bitstamp is selling XRP!,https://www.bitstamp.net,5,11,None,
27,1366401471,NemoNoko,Ripple is like a high-tech Mesopotamian tablet?,https://ripple.com/blog/ripple-and-the-purpose...,1,0,None,
28,1366403225,johnnymexico,"Hello! I would like to invest in ripple, but n...",None,1,0,None,[removed]
29,1366437682,[deleted],snowco.in BTC/XRP order book is open,None,1,0,None,I've added an order book BTC/XRP on https://sn...
...,...,...,...,...,...,...,...,...
44022,1523683962,nubpokerkid,Any exchange on which I can short XRP?,None,0,13,None,I want to sell some ripple that I own but are ...
44023,1523684837,AiryAndreGrande,Can we please start down voting and getting ri...,None,1,0,None,[removed]
44024,1523690708,djc2105,What questions should I ask the Ripple CEO? (G...,https://i.redd.it/x1ankkr8ttr01.jpg,1,0,None,
44025,1523691070,jackthehorse,[video] Is XRP a security?,https://bestcrypto.tv/657/is-ripple-xrp-a-secu...,0,1,None,
44026,1523692474,dailycupdate,Win Ripple Today! [Start Now],http://winmorecryptos.com,1,0,None,
44027,1523693585,AutoModerator,Daily Ripple/XRP Discussion Thread 04/14/18 [Q...,None,7,26,None,Hello! It's Saturday. Welcome to our daily dis...
44028,1523693938,Panosmek,Vote for XRP!,https://twitter.com/ClothingWhale/status/98491...,9,5,None,
44029,1523694332,Panosmek,You can now send XRP through Telegram!,https://twitter.com/baltazar223/status/9848749...,102,7,None,
44030,1523695492,JohnPNjui,Ripple (XRP) Still Holding Steady After Santan...,https://ethereumworldnews.com/ripple-xrp-still...,1,0,None,
44031,1523696581,iceeei,Ledger Nano S,None,3,6,None,"Hello good people, i just purchased one of the..."
44032,1523697579,free-interpreter,A Living Ledger Update: Marvel at the ledger i...,http://alivingledger.com,19,8,None,
44033,1523699735,Johnydj2,value of ripple,None,0,9,None,hey im debating on investing more with ripple ...
44034,1523700708,Qretxg,"A ""client"" bought 450 million XRP today, annou...",https://imgur.com/uwLgFDr,0,10,None,
44035,1523700918,JohnPNjui,"Why Ripple (XRP), Stellar (XLM), Verge (XVG) a...",https://ethereumworldnews.com/why-ripple-xrp-s...,0,1,None,
44036,1523701529,Qretxg,Someone just bought 0.9 billion XRP. That's ab...,https://imgur.com/34BU2Br,0,6,None,
44037,1523701534,Cryptocove254,Will Ripple InterLedger proposal to W3C Lift R...,https://ripplecoinnews.com/ripple-price-techni...,1,0,None,
44038,1523702400,Qretxg,XRP appreciates nearly 6 times against BTC in ...,https://imgur.com/uEBBLcs,0,1,None,
44039,1523702731,Brassmonkeyspinners,Bearableguy123s latest tweet... can we crack t...,https://i.redd.it/ik87hb00tur01.jpg,1,1,None,
44040,1523702973,Brassmonkeyspinners,Can anyone crack bearableguy123s latest tweet???,None,1,0,None,[removed]
44041,1523703168,Brassmonkeyspinners,Can anyone crack bearableguy123s new Twitter p...,None,4,7,None,[removed]
44042,1523703252,Behind_Crypto,"TradingView Script | have the 8, 13, 21 and 55...",https://uk.tradingview.com/script/KQk2EFDX-Fib...,1,0,None,
44043,1523703363,BurnAgainBurgers,Be wise of *pump and dump atempts*,None,1,2,None,[removed]
44044,1523703427,Qretxg,"A nice analogy from Tiffany Hayden: ""XRP is li...",https://twitter.com/haydentiff/status/92185237...,0,1,None,
44045,1523704176,Qretxg,Im leaving a statement from sbi here so the no...,https://imgur.com/hLtnPqu,0,5,None,
44046,1523704966,Charitypub,Ripple says its cryptocurrency XRP is not a se...,https://www.cnbc.com/2018/04/12/ripple-says-it...,1,0,None,
44047,1523706712,Qretxg,Is this why Ripple is likely to cripple Bitcoi...,https://imgur.com/SceuMTj,6,4,None,
44048,1523707312,Qretxg,WARNING: “TheBitcoinsNews.com” is hosting a fa...,http://coinagecrypt.com/?reqp=1&amp;reqr=nzcdY...,1,0,None,
44049,1523708358,moedamiche,an inquiry,None,1,0,None,[removed]
44050,1523708401,Qretxg,Ledger Wallet now supports XRP - A great hardw...,https://www.ledgerwallet.com/apps/ripple,0,4,None,
44051,1523712159,the_xrp_guy,Good morning friends! Keep on hodlin on!,None,1,0,None,[removed]